export const typography = {
  'title-xxl': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 700,
    lineHeight: '1.5',
    fontSize: '32px',
  },
  'title-xxl-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 800,
    lineHeight: '1.5',
    fontSize: '32px',
  },
  'title-xxl-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '32px',
  },
  'title-xl-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 800,
    lineHeight: '1.5',
    fontSize: '28px',
  },
  'title-xl-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '28px',
  },
  'title-l-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 800,
    lineHeight: '1.5',
    fontSize: '24px',
  },
  'title-l-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '24px',
  },
  'title-m-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 800,
    lineHeight: '1.5',
    fontSize: '20px',
  },
  'title-m-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '20px',
  },
  'title-s-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 800,
    lineHeight: '1.5',
    fontSize: '18px',
  },
  'title-s-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '18px',
  },
  'title-xs-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 800,
    lineHeight: '1.5',
    fontSize: '16px',
  },
  'title-xs-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '16px',
  },
  'text-xxl': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 400,
    lineHeight: '1.5',
    fontSize: '22px',
  },
  'text-xxl-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 700,
    lineHeight: '1.5',
    fontSize: '22px',
  },
  'text-xxl-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '22px',
  },
  'text-xl-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 700,
    lineHeight: '1.5',
    fontSize: '20px',
  },
  'text-xl-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '20px',
  },
  'text-xl': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 400,
    lineHeight: '1.5',
    fontSize: '20px',
  },
  'text-l-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 700,
    lineHeight: '1.5',
    fontSize: '18px',
  },
  'text-l-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '18px',
  },
  'text-l': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 400,
    lineHeight: '1.5',
    fontSize: '18px',
  },
  'text-m-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 700,
    lineHeight: '1.5',
    fontSize: '16px',
  },
  'text-m-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '16px',
  },
  'text-m': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 400,
    lineHeight: '1.5',
    fontSize: '16px',
  },
  'text-s': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 400,
    lineHeight: '1.5',
    fontSize: '14px',
  },
  'text-s-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 700,
    lineHeight: '1.5',
    fontSize: '14px',
  },
  'text-s-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '14px',
  },
  'text-xs': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 400,
    lineHeight: '1.5',
    fontSize: '12px',
  },
  'text-xs-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '12px',
  },
  'text-xs-bold': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 700,
    lineHeight: '1.5',
    fontSize: '12px',
  },
  'text-xxs': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 400,
    lineHeight: '1.5',
    fontSize: '10px',
  },
  'text-xxs-medium': {
    fontFamily: 'Arial, sans-serif',
    fontWeight: 500,
    lineHeight: '1.5',
    fontSize: '10px',
  },
} as const;
